#!/bin/bash -eu

# For details, see: https://qiita.com/hoto17296/items/69c832bf7628a6c85cc5

require() {
  if ! type $1 > /dev/null 2>&1; then
    echo "Please install $1." 1>&2
    exit 1
  fi
}
require aws
require peco
require jq

if [ -z "${AWS_PROFILE:-}" ]; then
  AWS_PROFILE=$(cat ~/.aws/config | grep '\[profile ' | sed -E 's/\[profile (.+)\]/\1/g' | peco --prompt 'AWS_PROFILE>')
fi
AWS_PROFILE=${AWS_PROFILE:-default}

SSO_AUTHENTICATION_URL=$(aws --profile ${AWS_PROFILE} configure get sso_authentication_url || true)
if [ -n "${SSO_AUTHENTICATION_URL}" ]; then
  echo -e "Open this URL in your browser to get the SAML Response string.\n${SSO_AUTHENTICATION_URL}\n"
  open ${SSO_AUTHENTICATION_URL}
fi

CONFIG_PATH="${HOME}/.aws/assume-role-with-saml-config/${AWS_PROFILE}.yml"
if [ ! -f "$CONFIG_PATH" ]; then
  echo "Config file is not found: ${CONFIG_PATH}" 1>&2
  exit 1
fi

read -n 8192 -p "SAML Response: " SAML_RESPONSE

CREDENTIALS=$(aws sts assume-role-with-saml --cli-input-yaml "$(cat ${CONFIG_PATH})" --saml-assertion ${SAML_RESPONSE})

echo -e "\nSucceeded!\nAdd the below to '~/.aws/credentials'.\n"

echo "[${AWS_PROFILE}]"
echo "aws_access_key_id = $(echo ${CREDENTIALS} | jq -r .Credentials.AccessKeyId)"
echo "aws_secret_access_key = $(echo ${CREDENTIALS} | jq -r .Credentials.SecretAccessKey)"
echo "aws_session_token = $(echo ${CREDENTIALS} | jq -r .Credentials.SessionToken)"
