#!/bin/sh

if [ -z "$NOTEBOOK_DIR" ]; then
  if [ -d "$PWD/notebooks" ]; then
    NOTEBOOK_DIR=$PWD/notebooks
  else
    NOTEBOOK_DIR=$PWD
  fi
fi

if [ "$1" == "-d" ]; then
  RUN_OPTION="-d"
else
  RUN_OPTION="-it"
fi

docker run --rm $RUN_OPTION \
    --name ${CONTAINER_NAME:-jupyter-anaconda3} \
    -h ${HOST:-localhost} \
    -p ${PORT:-8888}:8888 \
    -v $NOTEBOOK_DIR:/notebooks \
    continuumio/anaconda3 \
    jupyter notebook \
        --allow-root \
        --ip=0.0.0.0 \
        --NotebookApp.token='' \
        --notebook-dir=/notebooks
