#!/bin/sh

if [ "$HOME" = "$PWD" ]
then
  NOTEBOOK_DIR=$HOME/notebooks
else
  NOTEBOOK_DIR=$PWD
fi

docker run --rm -it \
    -v $NOTEBOOK_DIR:/notebooks \
    -p 8888:8888 \
    -h localhost \
    continuumio/anaconda3 \
    jupyter notebook \
        --allow-root \
        --ip=0.0.0.0 \
        --NotebookApp.token='' \
        --notebook-dir=/notebooks
