#!/bin/sh

docker run --rm -it \
    -v $(pwd):/notebooks \
    -p 8888:8888 \
    -h localhost \
    continuumio/anaconda3 \
    jupyter notebook \
        --allow-root \
        --ip=0.0.0.0 \
        --NotebookApp.token='' \
        --notebook-dir=/notebooks
