#!/bin/sh -eu

if [ ! -p /dev/stdin ]; then
  echo "Usage:"
  echo "  aws sts get-session-token [options] | source ${0}"
else
  json=$(cat - | tr -d '\n')
  export AWS_ACCESS_KEY_ID=$(echo ${json} | sed -E 's/^.*"AccessKeyId": *"([^"]+)".*$/\1/')
  export AWS_SECRET_ACCESS_KEY=$(echo ${json} | sed -E 's/^.*"SecretAccessKey": *"([^"]+)".*$/\1/')
  export AWS_SESSION_TOKEN=$(echo ${json} | sed -E 's/^.*"SessionToken": *"([^"]+)".*$/\1/')
  env | grep AWS
fi
